import manifest from './previews.json';

export interface PreviewMedia {
  poster: string;
  webm?: string;
  mp4?: string;
}

/** How the clip sits on a project card: as an image area at the top, or behind the text. */
export type PreviewStyle = 'top' | 'behind';
export const previewStyle: PreviewStyle = 'top';

/** Generated by `pnpm previews:capture` (scripts/capture-previews.mjs). */
const previews: Record<string, PreviewMedia> = manifest;

export function getPreview(projectId: string): PreviewMedia | undefined {
  return previews[projectId];
}
